In [1]:
import numpy as np

In [2]:
actualPos = [(1,1),(1,2),(1,3),(2,1),(2,2),(2,3),(3,1),(3,2),(3,3)]

In [3]:
class state:
    
    heuristics = 0 #h
    actual_cost = 0 #g
    cost = 0
    #parent= None
    
    
    def man(self,x1,y1,x2,y2):
        return abs(x1-x2)+abs(y1-y2)
    
    
    
    def __init__(self,sInfo,P ):
        self.state_info = sInfo
        print(self.state_info)
        self.parent = P
        
        
    def prepair(self):
        self.heuristics = self.calculate_H()
        
        if self.parent == 0:
            self.actual_cost = 0
            self.cost = self.actual_cost + self.heuristics
        else:
            self.actual_cost = self.parent.actual_cost + 1
            self.cost = self.parent.actual_cost + 1 + self.heuristics
    #-----------------------------------------------------------------Goal Test -----------------------------
    def checkGoal(self):
        if self.heuristic_cost == 0 :
            return True
        
    #------------------------------------------------------------------Manhatten Distance -------------------    
    def calculate_H(self):
        cost = 0
        for i in range(1,4):
            for j in range(1,4):
                #print(i,j)
                current_staied = self.state_info[i][j]
                #print(current_staied)
                current_staied -= 1
                if(current_staied) == -1: continue
                temp = actualPos[current_staied]
                cost+= self.man(i,j,temp[0],temp[1])
                #print(cost, str(current_staied))
        return cost
    
    
    #It expand the childs
    def expand(self):
        return cost
    

In [4]:
source = np.array([
    [0,0,0,0,0],
    [0,1,2,3,0],
    [0,4,5,0,0],
    [0,7,6,8,0],
    [0,0,0,0,0]
])

In [5]:
temp= state(source,source)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 0 0]
 [0 7 6 8 0]
 [0 0 0 0 0]]


In [6]:
#A = state(source,temp)
A = state(source, 0)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 0 0]
 [0 7 6 8 0]
 [0 0 0 0 0]]


In [7]:
A.heuristics

0

In [8]:
A.prepair()

In [9]:
A.state_info

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 0, 0],
       [0, 7, 6, 8, 0],
       [0, 0, 0, 0, 0]])

In [10]:
A.cost

3

In [11]:
A.actual_cost

0

In [12]:
A.heuristics

3

In [13]:
A.calculate_H()

3